### PR TITLE
modify proj4 package version

### PR DESCRIPTION
**Pull request by drnextgis**
Now if you try to install Proj4Leaflet with Bower it automatically install old version of proj4 - proj4#2.1.4.

### CODE REVIEW

**Comment by drnextgis** [comment]
@perliedman please check it

**Comment by perliedman** [comment]
@drnextgis Bower docs aren't very specific on this: https://github.com/bower/spec/blob/master/json.md#dependencies - it just refers to npm's version range docs. Since npm definitely supports the `^` operator, I would assume bower does too.

Since I don't use Bower, I have no means of testing this in practice.

**Comment by drnextgis** [comment]
I've checked. It works. Output of proj4js installation with `"proj4": "^2.0.0"` in bower.json:

```
$ bower install
bower leaflet#~0.7.2            cached git://github.com/Leaflet/Leaflet.git#0.7.7
bower leaflet#~0.7.2          validate 0.7.7 against git://github.com/Leaflet/Leaflet.git#~0.7.2
bower proj4#^2.0.0              cached git://github.com/proj4js/proj4js.git#2.3.12
bower proj4#^2.0.0            validate 2.3.12 against git://github.com/proj4js/proj4js.git#^2.0.0
bower proj4#^2.0.0             install proj4#2.3.12
bower leaflet#~0.7.2           install leaflet#0.7.7
```

With `"proj4": "~2.1.2"` was:

```
$ bower install
bower leaflet#~0.7.2            cached git://github.com/Leaflet/Leaflet.git#0.7.7
bower leaflet#~0.7.2          validate 0.7.7 against git://github.com/Leaflet/Leaflet.git#~0.7.2
bower proj4#~2.1.2              cached git://github.com/proj4js/proj4js.git#2.1.4
bower proj4#~2.1.2            validate 2.1.4 against git://github.com/proj4js/proj4js.git#~2.1.2
bower proj4#~2.1.2             install proj4#2.1.4
bower leaflet#~0.7.2           install leaflet#0.7.7
```

**Comment by perliedman** [comment]
@drnextgis thanks, misread your comment.

@semone I'll merge this unless you have any objections?

**Comment by semone** [comment]
@perliedman gogogo :smile:

**Comment by perliedman** [comment]
:tada: 

@drnextgis thanks for contributing this! Lets hope this will improve the situation for Bower users.

**Comment by tituomin** [comment]
It does, thanks! Could you make a release?

**Pull request merged**
