### PR TITLE
Automatic testing.

### PR DESCRIPTION
**Pull request by pthorin**
* Switched from jasmine to mocha
* Removed Leaflet from dependencies in package.json (#127)
* Use mocha-phantomjs for npm testing
* Added travis.yml

### CODE REVIEW

**Comment by pthorin** [comment]
@perliedman Do you have time to do a quick once-over on this?

**Comment by theashyster** [comment]
@pthorin Just FYI, looks good to me. Don't forget about this one though https://github.com/kartena/Proj4Leaflet/blob/master/examples/tms-tiled/index.html

**Comment by pthorin** [comment]
@theashyster it's in `71fc115` :)

**Comment by theashyster** [comment]
@pthorin Damn, ninja style. Great. :)

**Comment by perliedman** [comment]
@pthorin without having actually tested it, this looks :+1:

**Pull request merged**
