### PR TITLE
Leaflet proj refactor

### PR DESCRIPTION
**Pull request by semone**
Updated to use `leaflet 1.0.0-rc.3`

I updated leaflet and proj4 in the lib folder and pointed the examples to this folder. That makes it easier to update the examples sice you dont have to go into every example and change the url.

### CODE REVIEW

**Comment by pthorin** [comment]
There seems to be an issue with the attribution of examples/wms/script.js. I don't think the copyright is owned by Open Street Map.

**Comment by semone** [comment]
Maybe I should write OpenStreetMap Contributors instead? I went on what this link is saying. But if it should be correct it should say Contributors as well. 
https://www.havochvatten.se/hav/samordning--fakta/kartor--gis/karttjanster/karttjanster/havs-grundkartor.html

**Comment by pthorin** [comment]
Oh, sorry, my bad. I assumed, which is never good. But yes, "OpenStreetMap contributors" is the correct form.

**Comment by semone** [comment]
Now it should be fixed 👍

**Comment by perliedman** [comment]
Is it really desirable to have our own copy of Leaflet inside this repo? I usually prefer using some CDN, but I guess that can be debated.

**Comment by semone** [comment]
I was thinking no at first as well. I did it because in the future then you only have to update that leaflet version to check the examples and the tests, so it was only done to remove the step of updating all examples and test with the new CDN url. 

But maybe there is a better way of doing that? Using browserify maybe?

**Comment by perliedman** [comment]
Hm, I see your point. Avoiding to change the URL in a million places is also good :)

You can do it with Browserify, but then we'd need a build step, which makes it harder for people to just clone and check the examples.

So, I guess you've convinced me :smile:

**Comment by pthorin** [comment]
Good job!

**Pull request merged**
